# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Common types and protocol shared between server and client."""

from gpu_memory_service.common.protocol import (
    AllocateRequest,
    AllocateResponse,
    ClearAllRequest,
    ClearAllResponse,
    CommitRequest,
    CommitResponse,
    ErrorResponse,
    ExportRequest,
    FreeRequest,
    FreeResponse,
    GetAllocationRequest,
    GetAllocationResponse,
    GetAllocationStateRequest,
    GetAllocationStateResponse,
    GetLockStateRequest,
    GetLockStateResponse,
    HandshakeRequest,
    HandshakeResponse,
    ListAllocationsRequest,
    ListAllocationsResponse,
    MetadataDeleteRequest,
    MetadataDeleteResponse,
    MetadataGetRequest,
    MetadataGetResponse,
    MetadataListRequest,
    MetadataListResponse,
    MetadataPutRequest,
    MetadataPutResponse,
    recv_message,
    recv_message_sync,
    send_message,
    send_message_sync,
)
from gpu_memory_service.common.types import (
    RW_REQUIRED_OPS,
    STATE_ALLOWED_OPS,
    ConnectionMode,
    Operation,
    ServerState,
    StateEvent,
    StateSnapshot,
    derive_state,
)

__all__ = [
    # Protocol messages
    "AllocateRequest",
    "AllocateResponse",
    "ClearAllRequest",
    "ClearAllResponse",
    "CommitRequest",
    "CommitResponse",
    "ErrorResponse",
    "ExportRequest",
    "FreeRequest",
    "FreeResponse",
    "GetAllocationRequest",
    "GetAllocationResponse",
    "GetAllocationStateRequest",
    "GetAllocationStateResponse",
    "GetLockStateRequest",
    "GetLockStateResponse",
    "HandshakeRequest",
    "HandshakeResponse",
    "ListAllocationsRequest",
    "ListAllocationsResponse",
    "MetadataDeleteRequest",
    "MetadataDeleteResponse",
    "MetadataGetRequest",
    "MetadataGetResponse",
    "MetadataListRequest",
    "MetadataListResponse",
    "MetadataPutRequest",
    "MetadataPutResponse",
    "recv_message",
    "recv_message_sync",
    "send_message",
    "send_message_sync",
    # Types
    "ConnectionMode",
    "Operation",
    "RW_REQUIRED_OPS",
    "ServerState",
    "STATE_ALLOWED_OPS",
    "StateEvent",
    "StateSnapshot",
    "derive_state",
]
