# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# ClusterRole patch for power-aware planner
# Adds permissions to list and patch pods for setting power limit annotations

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamo-platform-dynamo-operator-planner
rules:
- apiGroups:
  - nvidia.com
  resources:
  - dynamocomponentdeployments
  - dynamographdeployments
  verbs:
  - get
  - list
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch

