# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# DynamoGraphDeploymentRequest for AI Configurator-based profiling
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeploymentRequest
metadata:
  name: sla-aic
spec:
  model: "Qwen/Qwen3-0.6B"
  backend: vllm

  # ProfilingConfig maps directly to the profile_sla.py config format
  profilingConfig:
    profilerImage: "nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.7.0.post2"
    config:
      # Sweep/profiling configuration
      sweep:
        # AI Configurator mode (fast simulation-based profiling)
        use_ai_configurator: true
        aic_system: h100_sxm
        aic_hf_id: "Qwen/Qwen3-0.6B"
        aic_backend_version: "0.11.0"

      # SLA targets for profiling
      sla:
        isl: 3000   # Input sequence length
        osl: 150    # Output sequence length
        ttft: 500.0 # Time To First Token target (milliseconds)
        itl: 30.0   # Inter-Token Latency target (milliseconds)

  # Deployment overrides for the auto-created DGD
  deploymentOverrides:
    workersImage: "nvcr.io/nvidia/ai-dynamo/vllm-runtime:0.7.0.post2"

  # Automatically create DynamoGraphDeployment after profiling
  autoApply: true
